name: Reusable WF - Build

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      image_name:
          required: false
          default: ${{ github.repository }}
          type: string

defaults:
  run:
    shell: bash

env:
  REGISTRY: ghcr.io

jobs:

  build-container-image:
    runs-on: ubuntu-latest
    permissions: write-all
    steps:

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ inputs.image_name }}


      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: |
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:${{ inputs.version }}
            ${{ env.REGISTRY }}/${{ inputs.image_name }}:dev
          labels: ${{ steps.meta.outputs.labels }}
